name: Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: read

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve
        uses: hmarr/auto-approve-action@v4.0.0
